name: learning github actions for cicd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing php 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - name: Checking php version
        run: php --version
